"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Suspense } from "react";

interface Idea {
  id: string;
  title: string;
  description: string;
}

interface VoteData {
  up: number;
  down: number;
}

function getMyVotes(): Set<string> {
  if (typeof window === "undefined") return new Set();
  try {
    const raw = localStorage.getItem("vts_myVotes");
    return raw ? new Set(JSON.parse(raw)) : new Set();
  } catch {
    return new Set();
  }
}

function saveMyVotes(ids: Set<string>) {
  try {
    localStorage.setItem("vts_myVotes", JSON.stringify([...ids]));
  } catch {}
}

function ArenaContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const shouldReset = searchParams.get("reset") === "1";

  const [ideas, setIdeas] = useState<Idea[]>([]);
  const [votes, setVotes] = useState<Record<string, VoteData>>({});
  const [myVotes, setMyVotes] = useState<Set<string>>(new Set());
  const [loadingIdeas, setLoadingIdeas] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [countdown, setCountdown] = useState<number | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  useEffect(() => {
    setMyVotes(getMyVotes());
    setHydrated(true);
  }, []);

  const generateIdeas = useCallback(async () => {
    setLoadingIdeas(true);
    try {
      const res = await fetch("/api/ideas", { method: "POST" });
      if (res.ok) {
        const data = await res.json();
        setIdeas(data.ideas);
        setVotes({});
        setMyVotes(new Set());
        saveMyVotes(new Set());
      }
    } catch {
    } finally {
      setLoadingIdeas(false);
    }
  }, []);

  useEffect(() => {
    if (!hydrated || autoGenerated) return;
    if (shouldReset) {
      setAutoGenerated(true);
      generateIdeas();
      return;
    }
    setAutoGenerated(true);
    (async () => {
      try {
        const [ideasRes, votesRes] = await Promise.all([
          fetch("/api/ideas"),
          fetch("/api/vote"),
        ]);
        const ideasData = await ideasRes.json();
        const votesData = await votesRes.json();
        if (ideasData.ideas && ideasData.ideas.length > 0) {
          setIdeas(ideasData.ideas);
          setVotes(votesData.votes || {});
        } else {
          generateIdeas();
        }
      } catch {
        generateIdeas();
      }
    })();
  }, [hydrated, shouldReset, autoGenerated, generateIdeas]);

  const handleVote = useCallback(
    async (ideaId: string, direction: "up" | "down") => {
      if (myVotes.has(ideaId)) return;
      try {
        const res = await fetch("/api/vote", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ ideaId, direction }),
        });
        if (res.ok) {
          const data = await res.json();
          setVotes(data.votes || {});
          const newMyVotes = new Set(myVotes);
          newMyVotes.add(ideaId);
          setMyVotes(newMyVotes);
          saveMyVotes(newMyVotes);
        }
      } catch {}
    },
    [myVotes]
  );

  const handleReset = useCallback(() => {
    router.push("/arena?reset=1");
  }, [router]);

  const getScore = useCallback(
    (ideaId: string) => {
      const v = votes[ideaId];
      return v ? v.up - v.down : 0;
    },
    [votes]
  );

  const totalVotes = useMemo(() => {
    return ideas.reduce((sum, idea) => {
      const v = votes[idea.id];
      return sum + (v ? v.up + v.down : 0);
    }, 0);
  }, [ideas, votes]);

  const allVoted = ideas.length > 0 && myVotes.size >= ideas.length;

  useEffect(() => {
    if (!allVoted || ideas.length === 0) return;
    setCountdown(3);
    const timer = setInterval(() => {
      setCountdown((prev) => {
        if (prev === null) return null;
        if (prev <= 1) {
          clearInterval(timer);
          router.push("/build");
          return null;
        }
        return prev - 1;
      });
    }, 1000);
    return () => clearInterval(timer);
  }, [allVoted, ideas.length, router]);

  if (!hydrated) return null;

  const sortedIdeas = [...ideas].sort(
    (a, b) => getScore(b.id) - getScore(a.id)
  );
  const maxScore =
    ideas.length > 0 ? Math.max(...ideas.map((i) => getScore(i.id)), 0) : 0;

  return (
    <div className="min-h-dvh" style={{ background: "#F9F9F9" }}>
      <nav className="border-b" style={{ borderColor: "#C8CDD1" }}>
        <div className="max-w-[1200px] mx-auto px-[24px] py-[16px] flex items-center justify-between">
          <Link
            href="/"
            className="font-bold text-[18px]"
            style={{ color: "#1B1B1B" }}
          >
            VoteToShip
          </Link>
          <span className="text-[14px]" style={{ color: "#797979" }}>
            Powered by GLM 5.1
          </span>
        </div>
      </nav>

      <main className="max-w-[800px] mx-auto px-[24px] py-[40px]">
        <div className="mb-[32px]">
          <h1
            className="text-[44px] font-extrabold leading-tight"
            style={{ color: "#1B1B1B" }}
          >
            Battle Arena
          </h1>
          <p className="text-[18px] mt-[6px]" style={{ color: "#797979" }}>
            Vote on every idea. The winner gets built live.
          </p>
          <div className="flex items-center gap-[12px] mt-[10px]">
            <span className="text-[13px]" style={{ color: "#797979" }}>
              {myVotes.size}/{ideas.length} voted
            </span>
            {totalVotes > 0 && (
              <>
                <span style={{ color: "#C8CDD1" }}>·</span>
                <span className="text-[13px]" style={{ color: "#797979" }}>
                  {totalVotes} total votes
                </span>
              </>
            )}
            <span style={{ color: "#C8CDD1" }}>·</span>
            <button
              onClick={handleReset}
              className="text-[13px] cursor-pointer underline"
              style={{ color: "#797979", background: "none", border: "none" }}
            >
              New battle
            </button>
          </div>
        </div>

        {countdown !== null && (
          <div
            className="text-center py-[16px] mb-[20px] rounded-[6px]"
            style={{ background: "#000001" }}
          >
            <p className="text-[20px] font-bold" style={{ color: "#fff" }}>
              All votes cast — building in{" "}
              <span style={{ color: "#facc15" }}>{countdown}</span>...
            </p>
          </div>
        )}

        {loadingIdeas && (
          <div className="space-y-[12px]">
            {Array.from({ length: 5 }).map((_, i) => (
              <div
                key={i}
                className="rounded-[6px] border p-[24px] flex items-center gap-[16px]"
                style={{ borderColor: "#C8CDD1", background: "#fff" }}
              >
                <div
                  className="text-[24px] font-bold w-[32px] text-center shrink-0"
                  style={{ background: "#e5e5e5", color: "#e5e5e5" }}
                >
                  {i + 1}
                </div>
                <div className="flex-1">
                  <div
                    className="h-[18px] w-[50%] rounded mb-[8px]"
                    style={{ background: "#e5e5e5" }}
                  />
                  <div
                    className="h-[14px] w-[80%] rounded"
                    style={{ background: "#f0f0f0" }}
                  />
                </div>
              </div>
            ))}
          </div>
        )}

        {!loadingIdeas && sortedIdeas.length > 0 && (
          <div className="space-y-[12px]">
            {sortedIdeas.map((idea, index) => {
              const score = getScore(idea.id);
              const isLeader = score === maxScore && score > 0;
              const rank = index + 1;
              const voted = myVotes.has(idea.id);
              return (
                <div
                  key={idea.id}
                  className="rounded-[6px] border p-[24px] flex items-start gap-[16px] relative"
                  style={{
                    borderColor: isLeader ? "#000001" : "#C8CDD1",
                    background: "#fff",
                    borderWidth: isLeader ? "2px" : "1px",
                    opacity: voted ? 0.7 : 1,
                  }}
                >
                  <div
                    className="text-[28px] font-extrabold shrink-0 w-[36px] text-right leading-none pt-[2px]"
                    style={{ color: isLeader ? "#000001" : "#C8CDD1" }}
                  >
                    {rank}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-[8px] mb-[4px]">
                      <h3
                        className="text-[18px] font-semibold truncate"
                        style={{ color: "#1B1B1B" }}
                      >
                        {idea.title}
                      </h3>
                      {isLeader && (
                        <span
                          className="shrink-0 text-[10px] font-bold px-[8px] py-[2px] rounded-full"
                          style={{ background: "#000001", color: "#fff" }}
                        >
                          WINNING
                        </span>
                      )}
                    </div>
                    <p
                      className="text-[14px] mb-[12px] leading-relaxed"
                      style={{ color: "#797979" }}
                    >
                      {idea.description}
                    </p>
                    <div className="flex items-center gap-[8px]">
                      <button
                        onClick={() => handleVote(idea.id, "up")}
                        disabled={voted || countdown !== null}
                        className="flex items-center gap-[4px] px-[14px] py-[6px] rounded-[22px] text-[13px] font-medium cursor-pointer border disabled:opacity-50 disabled:cursor-not-allowed"
                        style={{
                          borderColor: "#C8CDD1",
                          background: "transparent",
                          color: "#1B1B1B",
                        }}
                      >
                        ▲ {votes[idea.id]?.up ?? 0}
                      </button>
                      <button
                        onClick={() => handleVote(idea.id, "down")}
                        disabled={voted || countdown !== null}
                        className="flex items-center gap-[4px] px-[14px] py-[6px] rounded-[22px] text-[13px] font-medium cursor-pointer border disabled:opacity-50 disabled:cursor-not-allowed"
                        style={{
                          borderColor: "#C8CDD1",
                          background: "transparent",
                          color: "#797979",
                        }}
                      >
                        ▼ {votes[idea.id]?.down ?? 0}
                      </button>
                      <span
                        className="text-[16px] font-bold ml-auto tabular-nums"
                        style={{
                          color:
                            score > 0
                              ? "#1B1B1B"
                              : score < 0
                              ? "#c00"
                              : "#797979",
                        }}
                      >
                        {score > 0 ? "+" : ""}
                        {score}
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </main>

      <footer className="border-t py-[20px]" style={{ borderColor: "#C8CDD1" }}>
        <div className="max-w-[800px] mx-auto px-[24px] text-center">
          <p className="text-[13px]" style={{ color: "#797979" }}>
            Built for the Build with GLM 5.1 Challenge · Powered by GLM 5.1 ·{" "}
            <a
              href="https://mikacend.xyz"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#1B1B1B" }}
            >
              mikacend
            </a>
            {" · "}
            <Link href="/history" style={{ color: "#1B1B1B" }}>
              History
            </Link>
            {" · "}
            <Link href="/next" style={{ color: "#1B1B1B" }}>
              What's Next
            </Link>
          </p>
        </div>
      </footer>
    </div>
  );
}

export default function ArenaPage() {
  return (
    <Suspense>
      <ArenaContent />
    </Suspense>
  );
}
